# Define 'Configmap' to store non-sensitive database configuration 
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config  # name of ConfigMap, referenced in other files
data:
  comment: "'This is a general statement passed as environment variable' - Indrajit"