# Deploy a Service which defines a network access to a set of pods. 
# In the case of the master node, we only need to communicate through the port 9300 used for cluster communication.

# elasticsearch-master.service.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  ports:
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: master
---