# Service exposes Kibana default port 5601 to the environment and use NodePort to also expose a port 
# directly on the static node IP so we can access it externally.

# kibana.service.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    name: webinterface
  selector:
    app: kibana
---
