---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-web-ui
  namespace: monitoring
spec:
  # tls:
  #   - secretName: poc-wu-tls
  #     hosts:
  #       - poc.wu
  rules:
    - host: poc.wu
      http:
        paths:
          - path: /kibana
            backend:
              serviceName: kibana
              servicePort: 5601